version: '3.8'

services:
  mysql-backup:
    build: .
    container_name: mysql-backup-service
    restart: unless-stopped
    environment:
      # 必需的环境变量 - 请在.env文件中设置实际值
      - MYSQL_CONNECTIONS=${MYSQL_CONNECTIONS}
      - B2_APPLICATION_KEY_ID=${B2_APPLICATION_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME}
      
      # 可选的环境变量
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE:-0 4 * * *}
      - RETENTION_DAYS=${RETENTION_DAYS:-7}
      - HEALTH_CHECK_PORT=${HEALTH_CHECK_PORT:-8080}
      - RUN_INITIAL_BACKUP=${RUN_INITIAL_BACKUP:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    ports:
      - "${HEALTH_CHECK_PORT:-8080}:8080"
    
    volumes:
      # 挂载日志目录（可选）
      - ./logs:/var/log
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
